export const LOGIN = "LOGIN";
export const VERIFIED = "VERIFIED";
export const LOGOUT = "LOGOUT";
export const UPLOAD_PROFILE_PICTURE = "UPLOAD_PROFILE_PICTURE";
export const UPLOAD_COVER_PICTURE = "UPLOAD_COVER_PICTURE";
export const PROFILE_REQUEST = "PROFILE_REQUEST";
export const PROFILE_SUCCESS = "PROFILE_SUCCESS";
export const PROFILE_ERROR = "PROFILE_ERROR";
