export const LOGIN = "LOGIN";
export const VERIFIED = "VERIFIED";
export const LOGOUT = "LOGOUT";
export const UPLOAD_PROFILE_PICTURE = "UPLOAD_PROFILE_PICTURE";
export const UPLOAD_COVER_PICTURE = "UPLOAD_COVER_PICTURE";
